name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages:  libdbus-1-dev libusb-dev libhidapi-dev libhidapi-hidraw0 pkg-config libudev-dev libgtk-3-dev
        version: 1.0
          
    - name: "Install Rust"
      uses: dtolnay/rust-toolchain@stable
    - name: "Cache cargo"
      uses: Swatinem/rust-cache@v2
    - name: Build
      working-directory: ./razer_control_gui
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./razer_control_gui
      run: cargo test --verbose
